server:
  port: 8080
spring:
  ai:
    dashscope:
      api-key: sk-fec7e8ba4a8040be94d301f0fbc7fdb3

  datasource:
    url: jdbc:mysql://localhost:3306/shuzimali
    username: root
    password: 123456 #记得修改成自己本地数据库密码
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-handlers-package: cn.edu.zjweu.cs.shuzimali.typehandler
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true